stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv
    - src/preprocess.py
    outs:
    - data/processed/cleaned.csv
  train:
    cmd: python src/train.py
    deps:
    - data/processed/cleaned.csv
    - src/train.py
    outs:
    - models/random_forest.pkl
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - data/processed/cleaned.csv
    - models/random_forest.pkl
    - src/evaluate.py
    outs:
    - reports/confusion_matrix.png
    - reports/roc_curve.png
